services:
  server:
    image: softvence/calvinlockhart-server:latest
    platform: linux/amd64
    build:
      context: .
    container_name: calvinlockhart_api
    restart: always
    environment:
      DATABASE_URL: postgresql://iusdgjsdalkgjsdagklasghasdlkghsajklgh:fhsaaghkjdshgslkgdhsakgdhasklghskgjhsgjkghslgjhkghgklhsdgywpeoitwehaghsadg@db:5432/calvinlockhart_db?connection_limit=10&pool_timeout=30&pgbouncer=true

      JWT_SECRET: your_super_secret_herefjskdfjaskfjasfksrwerdv
      JWT_EXPIRES_IN: 90d
      RESET_TOKEN_EXPIRES_SECONDS: 900

      OTP_EXPIRES_MINUTES: 5

      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 465

      SMTP_USER: ctlockhart@gmail.com
      SMTP_PASS: wyuediwjbjffgezi

      CLOUDINARY_CLOUD_NAME: "dxkov6k4k"
      CLOUDINARY_API_KEY: "224666147412464"
      CLOUDINARY_API_SECRET: "zKtjdPv-kFsKolQKlalvP9GDmRM"
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "
      echo 'üèÅ Waiting for DB...';
      sleep 5;
      npx prisma migrate deploy;
      echo 'üöÄ Starting app...';
      npm run start:prod
      "

  db:
    image: postgres:16
    container_name: calvinlockhart_db
    restart: always
    environment:
      POSTGRES_USER: iusdgjsdalkgjsdagklasghasdlkghsajklgh
      POSTGRES_PASSWORD: fhsaaghkjdshgslkgdhsakgdhasklghskgjhsgjkghslgjhkghgklhsdgywpeoitwehaghsadg
      POSTGRES_DB: calvinlockhart_db
    volumes:
      - calvinlockhart_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U iusdgjsdalkgjsdagklasghasdlkghsajklgh -d calvinlockhart_db",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  calvinlockhart_db:
networks:
  default:
